builtin.c: add missing env.h include.
Spotted via clang warning:

builtin.c:243:6: warning: implicit declaration of function 'add_to_env' is
      invalid in C99 [-Wimplicit-function-declaration]
        r = add_to_env(CAR(args), CAR(CDR(args)), env);